gcc -fcf-protection=none -O0 -std=c17 -fno-jump-tables -Wno-unused-function -Wall -Wextra -Werror -ggdb -Isrc/core -Isrc/pack -I/home/clement/probes/encrypt/src -c src/core/elfstate.c -o build/elfstate.o
gcc -fcf-protection=none -O0 -std=c17 -fno-jump-tables -Wno-unused-function -Wall -Wextra -Werror -ggdb -Isrc/core -Isrc/pack -I/home/clement/probes/encrypt/src -c /home/clement/probes/encrypt/src/xor.c -o build/cx_xor.o
gcc -fcf-protection=none -O0 -std=c17 -fno-jump-tables -Wno-unused-function -Wall -Wextra -Werror -ggdb -Isrc/core -Isrc/pack -I/home/clement/probes/encrypt/src -c /home/clement/probes/encrypt/src/crypt.c -o build/cx_crypt.o
gcc -fcf-protection=none -O0 -std=c17 -fno-jump-tables -Wno-unused-function -Wall -Wextra -Werror -ggdb -Isrc/core -Isrc/pack -I/home/clement/probes/encrypt/src -c /home/clement/probes/encrypt/src/ctr.c -o build/cx_ctr.o
gcc -fcf-protection=none -O0 -std=c17 -fno-jump-tables -Wno-unused-function -Wall -Wextra -Werror -ggdb -Isrc/core -Isrc/pack -I/home/clement/probes/encrypt/src -c /home/clement/probes/encrypt/src/ecb.c -o build/cx_ecb.o
gcc -fcf-protection=none -O0 -std=c17 -fno-jump-tables -Wno-unused-function -Wall -Wextra -Werror -ggdb -Isrc/core -Isrc/pack -I/home/clement/probes/encrypt/src -c /home/clement/probes/encrypt/src/random.c -o build/cx_random.o
gcc -fcf-protection=none -O0 -std=c17 -fno-jump-tables -Wno-unused-function -Wall -Wextra -Werror -ggdb -Isrc/core -Isrc/pack -I/home/clement/probes/encrypt/src -c /home/clement/probes/encrypt/src/speck.c -o build/cx_speck.o
gcc -fcf-protection=none -O0 -std=c17 -fno-jump-tables -Wno-unused-function -Wall -Wextra -Werror -ggdb -Isrc/core -Isrc/pack -I/home/clement/probes/encrypt/src -c /home/clement/probes/encrypt/src/twill.c -o build/cx_twill.o
gcc -fcf-protection=none -O0 -std=c17 -fno-jump-tables -Wno-unused-function -Wall -Wextra -Werror -ggdb -Isrc/core -Isrc/pack -I/home/clement/probes/encrypt/src -c /home/clement/probes/encrypt/src/tessera.c -o build/cx_tessera.o
gcc -fcf-protection=none -O0 -std=c17 -fno-jump-tables -Wno-unused-function -Wall -Wextra -Werror -ggdb -Isrc/core -Isrc/pack -I/home/clement/probes/encrypt/src -c /home/clement/probes/encrypt/src/spn.c -o build/cx_spn.o
gcc -fcf-protection=none -O0 -std=c17 -fno-jump-tables -Wno-unused-function -Wall -Wextra -Werror -ggdb -Isrc/core -Isrc/pack -I/home/clement/probes/encrypt/src -c /home/clement/probes/encrypt/src/seal.c -o build/cx_seal.o
gcc -fcf-protection=none -O0 -std=c17 -fno-jump-tables -Wno-unused-function -Wall -Wextra -Werror -ggdb -Isrc/core -Isrc/pack -I/home/clement/probes/encrypt/src -c /home/clement/probes/encrypt/src/weft.c -o build/cx_weft.o
gcc -fcf-protection=none -O0 -std=c17 -fno-jump-tables -Wno-unused-function -Wall -Wextra -Werror -ggdb -Isrc/core -Isrc/pack -I/home/clement/probes/encrypt/src -c /home/clement/probes/encrypt/src/cipher.c -o build/cx_cipher.o
gcc -fcf-protection=none -O0 -std=c17 -fno-jump-tables -Wno-unused-function -Wall -Wextra -Werror -ggdb -Isrc/core -Isrc/pack -I/home/clement/probes/encrypt/src -c /home/clement/probes/encrypt/src/ripple.c -o build/cx_ripple.o
gcc -O0 -std=c17 -fcf-protection=none -fno-stack-protector -falign-functions=256 -Wall -Wextra -Werror -ggdb -Isrc/core -Isrc/pack -I/home/clement/probes/encrypt/src -c src/pack/elfpack.c -o build/elfpack.o
gcc -o ./elfpack build/elfpack.o build/elfstate.o build/cx_xor.o build/cx_crypt.o build/cx_ctr.o build/cx_ecb.o build/cx_random.o build/cx_speck.o build/cx_twill.o build/cx_tessera.o build/cx_spn.o build/cx_seal.o build/cx_cipher.o build/cx_ripple.o build/cx_weft.o
env ELFPACK_SEAL=1 ./elfpack
